export const SYSTEM_AJAX_START = "SYSTEM_AJAX_START";
export const SYSTEM_NAVIGATE = "SYSTEM_NAVIGATE";
export const SYSTEM_ALERT_USER = "SYSTEM_ALERT_USER";
export const SYSTEM_ALERT_CLEAR = "SYSTEM_ALERT_CLEAR";

export const AUTH_SESSION = "AUTH_SESSION";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_FAILURE = "AUTH_FAILURE";


